@baseurl = http://localhost:8000
@product_id = 263d791e-8373-48a1-ae2b-0654c5605c6f

# @name create_product
POST {{baseurl}}/products
Content-Type: application/json

{
  "name": "Xbox One",
  "price": 3000
}

###

# @name get_products
GET {{baseurl}}/products
Content-Type: application/json

###

# @name get_product_by_id
GET {{baseurl}}/products/{{product_id}}
Content-Type: application/json

###

# @name update_product
PUT {{baseurl}}/products/{{product_id}}
Content-Type: application/json

{
  "name": "PlayStation 2",
  "price": 100
}

###

# @name delete_product
DELETE {{baseurl}}/products/{{product_id}}
Content-Type: application/json

###

# @name ping
GET {{baseurl}}/ping
Content-Type: application/json
