@baseurl = http://localhost:8000
@product_id = 68c9e51d-7e61-46f8-adae-3231ea39dc82

# @name create_product
POST {{baseurl}}/products
Content-Type: application/json

{
  "name": "PlayStation 5",
  "price": 1000
}

###

# @name get_products
GET {{baseurl}}/products
Content-Type: application/json

###

# @name get_product_by_id
GET {{baseurl}}/products/{{product_id}}
Content-Type: application/json

###

# @name update_product
PUT {{baseurl}}/products/{{product_id}}
Content-Type: application/json

{
  "name": "PlayStation 2",
  "price": 100
}

###

# @name delete_product
DELETE {{baseurl}}/products/{{product_id}}
Content-Type: application/json
