@baseurl = http://localhost:8000
@user_id = 2a1f86f5-e536-47ee-ac44-174f014798d1

# @name create_user
POST {{baseurl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "123456"
}

###

# @name login
POST {{baseurl}}/users/login
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "123456"
}
